/**
 * Device Manager
 * Device Manager API CRUD
 *
 * OpenAPI spec version: 1.0.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Place { 
    /**
     * Place Primary Key
     */
    id?: number;
    level?: number;
    lat: number;
    lon: number;
    creation_date?: Date;
    /**
     * Group Primary Key
     */
    group_id: number;
    group_inner_id: number;
    custom_id?: string;
    network_id?: string;
}

