/**
 * Test API CRUD
 *
 * OpenAPI spec version: 1.0.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ApiResponse {
  reason: ReasonEnum;
  message: string;
  data?: any;
}

export type ReasonEnum = 'not_found' | 'server_error' | 'invalid_field' | 'created' | 'no_data' | 'not_implemented' | 'ok' | 'restricted';
export const ReasonEnum = {
  NotFound: 'not_found' as ReasonEnum,
  ServerError: 'server_error' as ReasonEnum,
  InvalidField: 'invalid_field' as ReasonEnum,
  Created: 'created' as ReasonEnum,
  NoData: 'no_data' as ReasonEnum,
  NotImplemented: 'not_implemented' as ReasonEnum,
  Ok: 'ok' as ReasonEnum,
  Restricted: 'restricted' as ReasonEnum,
};
